### ISSUE TITLE
CCN-lite's git history is broken

### ISSUE THREAD

**Issue by miri64** [cn-uofbasel/ccn-lite#115]
As pointed out in #114 some changes were removed (accidentally). With some analysis I identified 871175a as the culprit. It merged [timeout_prevention](https://github.com/cn-uofbasel/ccn-lite/tree/timeout_prevention) into master, but it seems like that merge conflicts were not resolved properly. Its parent that was previously master is 4cec945 and you can easily spot, that changes to certain files are not available anymore:

```
$ git log --oneline 4cec945 -- src/ccnl-core.c | grep a6045be # commit from #114
a6045be cache: remove oldest value and do not overrun
$ git log --oneline 871175a -- src/ccnl-core.c | grep a6045be | wc -l
0
```

**Comment by miri64** [comment]
From my (superficial) analysis I would guess, that any change between 9e48d32..4cec945 is affected by this.

```
$ git log --oneline 9e48d32..4cec945 --no-merges | wc -l
43
```

**Comment by blacksheeep** [comment]
I applied #114 manually. I still get a list of no-merged entires. 
But checking the code I found the code seems to be available.
So is only the history log broken?
