### ISSUE TITLE
CCN-Lite Relay Arduino

### ISSUE THREAD

**Issue by umair90** [cn-uofbasel/ccn-lite#116]
I have installed ccn-lite on Arduino. I see that it has already predefined content under /mac/temp.
Now i am am trying to peek from unix using the command below

$CCNL_HOME/bin/ccn-lite-peek -s ndn2013 -u ArduinoIP/6363 /mac/temp \ | $CCNL_HOME/bin/ccn-lite-pktdump

![arduino-serial display](https://cloud.githubusercontent.com/assets/5734439/24187907/7e57dee0-0f22-11e7-8d3b-9cf269851b30.png)

 returning me "re-sending interest".

![response](https://cloud.githubusercontent.com/assets/5734439/24187904/7e538d04-0f22-11e7-9846-fb25345f6bba.png)

Can someone tell what is wrong?
Any help will be highly appreciated. 
@OlegHahm @blacksheeep @tschudin

**Comment by blacksheeep** [comment]
Closed, since Arduino support was replaced with RIOT support in V2
