### ISSUE TITLE
Asking about Cache strategy in OMNeT

### ISSUE THREAD

**Issue by hanyabaim** [cn-uofbasel/ccn-lite#125]
Hello, i am new in ccn-lite. I am doing a research in ccn using omnet simulator. I've tried to do simulation using 4 client and 4 router, and on the cache strategy used there are LCE. But I am confused which code indicates that the cache strategy is used? Please help me. Thanks

**Comment by blacksheeep** [comment]
What do you mean by "cache strategy"?

**Comment by blacksheeep** [comment]
CCNL V2 has currently no omnet support

**Comment by hanyabaim** [comment]
Dear Mr.Christopher Scherb,

My name is Ibrahim from Brawijaya University, Indonesia.
Thank you for answer my question. I have completed my final project last
month and this is my first time to use CCNL in omnet. At that time, i was
very confused because i learned everything i know in CCNL alone and no one
of friends or my teachers know about this. Because of that, i am wrote a
question on github but no one respond. Maybe because my english is not good
enough to give a more detail explain. But, thank you very much to inform me
about CCNL V2. Maybe i will do some project with that, but i dont know
when. Thanks you Mr.Christopher, i really appreciate for your answer and
your information. God Bless You.

sincerely,
Ibrahim
