### ISSUE TITLE
handling of interest lifetime in ccn-lite

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#147]
Hi,

NDN defines in its packet specification a [interest lifetime](http://named-data.net/doc/NDN-TLV/current/interest.html#interestlifetime).  I've skimmed through the code and was wondering 

1.  If it is possible to set the lifetime by yourself? It always seems to be set to 0x0FA0
2. The lifetime does not seem to be evaluated at all. At least I couldn't find any functionality in respective functions such as ``ccnl_fwd_handleInterest``.  Or am I looking in the wrong place?

TIA
 Michael

**Comment by blacksheeep** [comment]
You are right, the interest lifetime for NDN is not handled, yet.

**Comment by cgundogan** [comment]
fixed by #185
