### ISSUE TITLE
provide a single declaration of function local_producer

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#148]
Would it make sense to declare the function
```C
int local_producer(struct ccnl_relay_s *relay, struct ccnl_face_s *from, 
              struct ccnl_pkt_s *pkt);
```
in a single header and remove the declarations in

* src/ccnl-fwd/src/ccnl-fwd.c
* src/ccnl-riot/include/ccn-lite-riot.h
* src/ccnl-lnxkernel/ccn-lite-lnxkernel.c
* src/ccnl-unix/include/ccnl-unix.h

As far as I can see every "system" (unix, linux kernel, android, riot, ...) CCN-lite supports would need a concrete implementation (in a sense of OO speak). Since a concrete implementation would only be build for a single target there would be no clashes with the build system (errors on multiple implementations of the same function) - afair, this is already the case for example for ccnl-unix.c (which has a definition which just returns 0) and riot. Or am I missing something?

If that's okay, I would move the function to a single header and clean up the 're-declarations' and open a PR.

**Comment by blacksheeep** [comment]
Done in #156
