### ISSUE TITLE
multiple definitions of inter_{ccn,pkt}_interval

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#151]
Hi, 

I'm going through the necessary changes for #148 and noticed that inter_ccn_interval is defined multiple times through out the ccn-lite code, e.g.
```
src/ccn-lite-simu.c:331:static int inter_ccn_interval = 0; // in usec
src/ccnl-android/native/src/ccn-lite-android.c:193:static int inter_ccn_interval = 0; // in usec
src/ccnl-lnxkernel/ccn-lite-lnxkernel.c:314:int inter_ccn_interval = 100;
src/ccnl-unix/include/ccnl-unix.h:41:static int inter_ccn_interval = 0; // in usec
```
The definition of inter_ccn_interval is (despite the line number) not within a function. The same goes for inter_pkt_interval
```
src/ccnl-android/native/src/ccn-lite-android.c:194:static int inter_pkt_interval = 0; // in usec
src/ccnl-unix/include/ccnl-unix.h:42:static int inter_pkt_interval = 0; // in usec
```
Is there any reason for this? I'm just asking since the build process fails on me about "defined but not used variable" errors.

TIA
 Michael

**Comment by blacksheeep** [comment]
I think, the reason is legacy, and can be transformed into non global variables.

**Comment by mfrey** [comment]
I think this is partially true. One version of ``inter_pkt_interval`` is defined in ``ccnl-unix.h`` and simply used in ``ccnl-unix.c`` in a function call. The ``ccn-lite-relay.c`` file includes ``ccnl-unix.h`` and also uses the variable, i.e.
```
src/ccnl-relay/ccn-lite-relay.c:202:            inter_pkt_interval = atoi(optarg);
```
I'm actually not sure how this affects the unix part of ccn-lite after all. If I would make this a local variable, the variable would never be changed iff the main function in ccn-lite-relay.c is used for settting the variable.

However, I'm a bit puzzled that the build process fails for me at this point since the variable is clearly used in the source file (and apparantly also in other translation units). I had hoped not to look into the build system ...

**Comment by blacksheeep** [comment]
Could inter_pkt_interval be placed inside the relay data strucure, so that is available in ccn-lite-relay and in ccnl-unix?

**Comment by mfrey** [comment]
Why does ccnl-mgmt.c does this
```C
2132     MGMT:
2133     ccnl_mgmt_handle(ccnl, orig, prefix, from, cmd, 1);
2134     (void) lasthour;
2135     (void) inter_ccn_interval;
2136     (void) inter_pkt_interval;                                                                                                                  
2137     return 0;
```
Line 2135 and 2136 are the only lines where the variables are "used". Since in line 48 the ccnl-unix.h header with the global variables is included - so this basically mutes the 'unused variable' compiler warnings. 

Apparently, if you have a header which contains static variable declaration/definitions each source file will get it's **own copy of the static variable** with scope bound to the corresponding source file. 

So if we have **n** source files which include the same header file with the static variable  **inter_{ccn,pkt}_interval** definitions than **n** different copies of the variables will be created, each bound to the scope of the corresponding source file. Ugh.

**Comment by mfrey** [comment]
> Could inter_pkt_interval be placed inside the relay data strucure, so that is available in ccn-lite-relay and in ccnl-unix?

The variable gets never updated in ccnl-unix, so we don't need to do this (see my previous comment). Also, I would refrain from adding more members to the relay struct.
