### ISSUE TITLE
travis build is broken

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#154]
Hi, 

the travis build is broken since 063fd8ad7e74f24410ef8fd9e23673c532500df5 which seems totally unrelated to the overall issue (the commit just adds some authors to the readme). I've tried to understand the issue in my fork, but the travis ui doesn't show any build plans, branches, etc. so it kind of hard to debug/test.

Do you already have an idea what causes the issue? 

TIA
 Michael

**Comment by blacksheeep** [comment]
Travis is broken for some time, even before we started CCNL-V2.
I think the travis system has to be completely rewritten, instead of trying to fix some stuff.

On big problem is, that the build server are using extreme old software versions.

**Comment by mfrey** [comment]
Does travis "work" for you in your personal fork? That's how it looks for me in my personal fork. It even fails to "recognize" branches

![image](https://user-images.githubusercontent.com/237157/35378480-3b2e3266-01b3-11e8-8f58-0f4be4af2946.png)

**Comment by blacksheeep** [comment]
It only runs on the master branch and additionally it checks pull requests

**Comment by mfrey** [comment]
> It only runs on the master branch and additionally it checks pull requests

I've assumed that it would show other existing branches as well. I've triggered a manual build, which "runs" for over an hour now ("waiting to be queued, waiting to start", ...)

**Comment by blacksheeep** [comment]
Yeah, I think there is also a problem with travis itself, we often end up with extrem slow execution for tests on Apple's OS.

I think what we have to do is redefine some tests and run them using new scripts.

**Comment by blacksheeep** [comment]
I removed the broken travis and replaced it with a semaphoreci (much faster).
Only build testing yet. Functionality testing is missing.
