### ISSUE TITLE
NDN-TLV: Scope TLV ?

### ISSUE THREAD

**Issue by cgundogan** [cn-uofbasel/ccn-lite#179]
For the ndn tlv parser, I can find several palces, where a Scope TLV is handled (see https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-pkt/include/ccnl-pkt-ndntlv.h#L44). However, in [[1]](https://named-data.net/doc/ndn-tlv/types.html) and [[2]](https://named-data.net/doc/ndn-tlv/interest.html), I cannot find a Scope TLV.

So what is this Scope TLV used for, and are there references somewhere that I missed?

Any hints @blacksheeep @cmarxer, anyone else?

**Comment by blacksheeep** [comment]
in [1] you will find scope as reserved. 

![image](https://user-images.githubusercontent.com/3641597/35912667-811481dc-0bfd-11e8-9617-9df0dfdf5413.png)
