### ISSUE TITLE
[discussion] make pull requests great again

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#188]
Hi,

I was wondering if we could disable "push to master", so only a PR which got approved gets into master? Also, PRs deserve to get a review and should not merged on a trust-level (and we should get tests back up running as soon as possible). This is lously based on [gitflow](http://nvie.com/posts/a-successful-git-branching-model/). Ideas, comments, suggestions?

Best, 
 Michael

**Comment by blacksheeep** [comment]
I support this.
I quickly checked the settings for that:
![image](https://user-images.githubusercontent.com/3641597/36035028-1170428e-0db6-11e8-9f39-8d57b203a9ce.png)

What should we activate?

**Comment by cgundogan** [comment]
the current settings in this screenshot look actually quite OK. @mfrey ?

**Comment by mfrey** [comment]
Looks good to me!

**Comment by blacksheeep** [comment]
Ok I will activate that
