### ISSUE TITLE
erroneous check for duplicate content in ccnl_content_add2cache

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#200]
Hi,

I wrote a local producer function which stores content created on the fly (e.g. sensor readings) in the cache. At some point in this function, I'm calling ``ccnl_content_add2cache`` which is also used by the ``ccnl_cont`` command in RIOT. 

With some surprise I've noticed that "same" content added via  ``ccnl_content_add2cache`` is added multiple times. Same refers here to multiple entries of ``/some/interest/example => 42``, but also another interest with a different content is possible, e.g. ``/some/interest/example => 23`` (besides the previous one).

I've checked the code and apparently the check for duplicate entries is performed in ``ccnl_content_add2cache`` here:
```C
 552     for (cit = ccnl->contents; cit; cit = cit->next) {
 553         if (c == cit) {
 554             DEBUGMSG_CORE(DEBUG, "--- Already in cache ---\n");
 555             return NULL;
 556         }
 557     }
```

I don't know if it is a general misunderstanding on my behalf, but I assumed that there is a unique relationship between interest and content, so a plain interest matches exactly one content (at least for CCNx (I'm aware that NDN introduces the concept of ``ChildSelector``)). 

The ``if`` statement just checks if the same pointer is not passed to the function twice. Is it not necessary to check actually for the prefix and the content? Maybe, I'm missing the point?

TIA
 Michael

**Comment by blacksheeep** [comment]
I think the check is wrong. it compares addresses instead of content. 

in the forwarding pipeline the check is correct:
ccnl-fwd.c:

```C
100    for (c = relay->contents; c; c = c->next) {
101        if (buf_equal(c->pkt->buf, (*pkt)->buf)) {
102           DEBUGMSG_CFWD(TRACE, "  content is duplicate, ignoring\n");
103            return 0; // content is dup, do nothing
104        }
105   }
```

**Comment by mfrey** [comment]
You probably want to check the prefix as well (and not just the buffer itself)

**Comment by blacksheeep** [comment]
Good Point. So Buffer contains the entire binary data. This do not prevent
you from adding different content with the same name twice.

In general, checking the prefix should be the way to go?

Michael Frey <notifications@github.com> schrieb am Fr., 23. Feb. 2018,
00:52:

**Comment by mfrey** [comment]
I've briefly checked and there is a ``ccnl_prefix_cmp`` function which can up to three distinct checks (``CMP_EXACT, CMP_MATCH, CMP_LONGEST``). 

We probably have to check which ICN flavor is used and check how duplicate content is detected. As far as I remember some ICN flavors allow to have wildcards. 

Does anybody have the CCNx specification? Since Cisco took over CCNx, most parts of the specification are gone.
