### ISSUE TITLE
How to port ccn-lite to Contiki-OS?

### ISSUE THREAD

**Issue by fzy-Line** [cn-uofbasel/ccn-lite#205]
CCN-lite currently supports five platforms, but isn't support Contiki-OS which is a open source OS for the IoT. A few years ago, there was a tutorial about CCNx for Contiki, but CCNx  is no longer appropriate. I want to know how to port ccn-lite to Contiki-OS. Thanks!

**Comment by cmarxer** [comment]
You might be interested in this paper: http://conferences2.sigcomm.org/acm-icn/2016/proceedings/p221-ahlgren.pdf

**Comment by mfrey** [comment]
There is support for RIOT, another OS for the IoT. While the programming model between the two differ (threads vs. events/protothreads), the RIOT adapter in CCN-lite might be a good starting point. Take a look [here](https://github.com/cn-uofbasel/ccn-lite/tree/master/src/ccnl-riot)

**Comment by fzy-Line** [comment]
@cmarxer thank you! I had read this paper, but this paper don't explianhow to port ccn-lite to contiki and  their code isn't open source too.

**Comment by fzy-Line** [comment]
@mfrey thank you! I know that RIOT is a friendly and excellently open source OS, but I find it don't support IEEE 802.15.4E TSCH that I am research on. The contiki OS support TSCH and I have been learning contiki for awhile, so I want to use this OS for my research.

**Comment by PeterKietzmann** [comment]
@fzy-Line I received your mail, but let's keep this discuss public.  All information about the purpose, open issues and status of this PR can be found [there](https://github.com/RIOT-OS/RIOT/pull/8570). As you can see, porting the whole IPv6 stack to RIOT is the first step. Later, we'd like to extract only the MAC layer. Basically we lack man power and I'm awaiting a review from one of the core maintainers of OpenWSN (@changtengfei). If you have capacities I'd be more than happy receiving support from you in form of testing and reviewing. 

If you have further questions to that port, just comment in the above mentioned PR. If you consider starting with RIOT, don't hesitate to ask for help in terms of first steps, getting started or whatever...

**Comment by mfrey** [comment]
@fzy-Line Can we close this issue or do you require further details for porting contiki to ccn-lite?

**Comment by fzy-Line** [comment]
@PeterKietzmann Thanks for your help! I will continue to  focus on your work.

**Comment by fzy-Line** [comment]
@mfrey I expect someone can give me more information, so please give me some time. I will close this issue three days later. Thank you very much!
