### ISSUE TITLE
Remove IOTTLV

### ISSUE THREAD

**Issue by blacksheeep** [cn-uofbasel/ccn-lite#212]
The IOTTLV packet format is not used and not stable, should be removed

**Comment by OlegHahm** [comment]
That was the TLV proposed by Cisco for constrained networks, right?

**Comment by blacksheeep** [comment]
Yes it is.

**Comment by mfrey** [comment]
> That was the TLV proposed by Cisco for constrained networks, right?

Any thoughts about removing IOTTLV from CCN-lite?

**Comment by blacksheeep** [comment]
No thoughts from my side. I do not know anyone using it. And I think there is no official standard for that.

**Comment by mfrey** [comment]
@OlegHahm Any thoughts?

Removal of IOTTLV can be tracked over [here](https://github.com/mfrey/ccn-lite/tree/rm-iottlv)
