### ISSUE TITLE
Built-in HTTP server not being compiled

### ISSUE THREAD

**Issue by Wojtek242** [cn-uofbasel/ccn-lite#217]
The feature list and tutorial mention that an in-built HTTP server is available at http://127.0.0.1:6363/. However, upon starting a relay I could not access anything under that address. I discovered that nothing was listening on port 6363. I noticed that USE_HTTP_STATUS has been disabled. Is there a good reason for it? I found that I can get it to work on Linux by adding a few missing includes: https://github.com/Wojtek242/ccn-lite/commit/a18d983fcb7bdbc1ea2316b438f0ff7b3b644cd3.

**Comment by blacksheeep** [comment]
thanks for the input, I enabled the http server on unix as default.
