### ISSUE TITLE
value stored in variable pos is never read in function get_pendint_dump

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#272]
The value stored in variable ``pos`` is never read in function ``get_pendint_dump``, i.e.
```C
490 int
491 get_pendint_dump(int lev, void *p, char **out){
492     struct ccnl_relay_s *top = (struct ccnl_relay_s    *) p;
493     struct ccnl_interest_s *itr = (struct ccnl_interest_s *) top->pit;
494     struct ccnl_pendint_s  *pir = (struct ccnl_pendint_s  *) itr->pending;
495 
496     int pos = 0, line = 0;
497     (void)lev;
498     while (pir) {
499 //        INDENT(lev);
500         pos = 0;
501         pos += sprintf(out[line] + pos, "%p PENDINT next=%p face=%p last=%d",
502                        (void *) pir, (void *) pir->next,
503                        (void *) pir->face, pir->last_used);
504         pir = pir->next;
505         ++line;
506     }
507     return line;
508 }
```
The value is assigned in line 501 but reset by line 500 for each iteration. Shall we remove the ``pos = 0`` statement. Any thoughts?

**Comment by blacksheeep** [comment]
question now is, can this value be removed, has it any meaning to be conidered?

**Comment by mfrey** [comment]
> question now is, can this value be removed, has it any meaning to be conidered?

I'm not sure if I understand you correctly. The idea probably was to check the return code of sprintf (which would have been the number of bytes written or a negative value in case of an error) and reset the return code to zero for the next iteration. However, ``pos`` strikes me as a rather ambiguous name for such a variable and it also does not really clarify why someone would actually add ``pos`` to the content of ``out[line]``. 

I vote for removing the ``pos`` variable and replace (if possible) the ``sprintf`` call with an snprintf`` call. I probably also would make line an unsigned int such as ``uint32_t``.
