### ISSUE TITLE
overflow in debug_malloc

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#274]
#### Description
There is a potential overflow in ``debug_malloc`` in file ``ccnl-malloc.c``
```C
struct mhdr *h = (struct mhdr *) malloc(s + sizeof(struct mhdr));
```
#### Steps to reproduce the issue
If you pass as size``INT_MAX -  sizeof(struct mhdr) + 1 `` to the function it will trigger the overflow. 

Thanks to Eric Sesterhenn from X-41 D-Sec for pointing this out.

**Comment by blacksheeep** [comment]
Fixed by Michael Frey in PR #276.
