### ISSUE TITLE
I want to use CCN-lite for sending content from one computer to another.

### ISSUE THREAD

**Issue by ericxiao77** [cn-uofbasel/ccn-lite#289]
#### Description
Example: Cannot use CCN-lite for sending content from one computer to another.

#### Steps to reproduce the issue

I followed the tutorial.md, produced content on computer B（the OS is Ubuntu 16.04）,started ccn-lite-relay for node A on computer A（it is raspberry pi，the OS is Ubuntu Mate），started ccn-lite-relay for node B on computer B;  created the face and a forwarding rule at node A on computer A,sended Interest for Name /ndn/test/mycontent/ to A on computer A.But it did not work,“resend interest ，time out” show in the terminal.Thank you for giving me some suggestions. 

#### Expected results
Example:Can use CCN-lite for sending content from one computer to another

**Comment by ericxiao77** [comment]
Mfrey and blacksheeep, thank you very much.You are so nice！

**Comment by ericxiao77** [comment]
Mfrey and blacksheeep, thank you very much.You are so nice！

**Comment by ericxiao77** [comment]
Mfrey and blacksheeep, thank you very much.You are so nice！

**Comment by mfrey** [comment]
> You are so nice！

Does it work?

**Comment by ericxiao77** [comment]
OK,I will.
