### ISSUE TITLE
cmocka.h cannot be found

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#299]
User @ericxiao77 reported an issue on compiling tests for ccn-lite. A snippet from the shell output
```bash
[ 95%] Building C object test/ccnl-core/CMakeFiles/test_interest.dir/test_interest.c.o
/home/pi0/ccn-lite/test/ccnl-core/test_interest.c:4:20: fatal error: cmocka.h: 
No such file or directory compilation terminated.
test/ccnl-core/CMakeFiles/test_interest.dir/build.make:62: recipe for target 
'test/ccnl-core/CMakeFiles/test_interest.dir/test_interest.c.o' failed
make[2]: *** [test/ccnl-core/CMakeFiles/test_interest.dir/test_interest.c.o] Error 1
CMakeFiles/Makefile2:985: recipe for target
 'test/ccnl-core/CMakeFiles/test_interest.dir/all' failed
make[1]: *** [test/ccnl-core/CMakeFiles/test_interest.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mfrey** [comment]
> fatal error: cmocka.h:  No such file or directory compilation terminated.

@ericxiao77 have you installed cmocka on your system?

**Comment by ericxiao77** [comment]
I checked the system and did not install cmocka, now I build properly.I am a newcomer to ccn-lite, thank you for your patience and your help!

**Comment by mfrey** [comment]
> I checked the system and did not install cmocka, now I build properly.I am a newcomer to ccn-lite, 
> thank you for your patience and your help!

No worries!
