### ISSUE TITLE
replace calls to atoi with strtol

### ISSUE THREAD

**Issue by mfrey** [cn-uofbasel/ccn-lite#319]
#### Description
 The function ``atoi`` can invoke undefined behavior upon error. See also [C11 7.22.1.2](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1494.pdf). The corresponding calls would be
```C
/** atoi */
(int)strtol(nptr, (char **)NULL, 10)
/** atol */
strtol(nptr, (char **)NULL, 10)
/** atoll */
strtoll(nptr, (char **)NULL, 10)
```

**Comment by blacksheeep** [comment]
How many a calls of atoi are left in the code?

**Comment by mfrey** [comment]
> How many a calls of atoi are left in the code?

$ git grep atoi | wc -l
      42

Seems a reasonable task?

**Comment by blacksheeep** [comment]
I agree, that we have to replace atoi.

**Comment by mfrey** [comment]
> I agree, that we have to replace atoi.

Same goes for atof.

```C
$ git grep atof | wc -l
5
```
