### ISSUE TITLE
Unable to build for Unix

### ISSUE THREAD

**Issue by ath-90** [cn-uofbasel/ccn-lite#370]
#### Description
Cannot build CCN-lite for Unix.

#### Steps to reproduce the issue
Following the official readme for Unix

#### Expected results
CCN-lite builds for Unix.
![Screenshot from 2020-02-14 17-01-43](https://user-images.githubusercontent.com/43179994/74527451-b9688e00-4f4b-11ea-823a-21beee2a2439.png)

**Comment by blacksheeep** [comment]
Thanks for the hint.
I see, cmocka is missing in the dependencies, I updated the readme, which should fix this bug.
