### ISSUE TITLE
Support for CCN-lite with the OMNeT++ framework

### ISSUE THREAD

**Issue by PeterKietzmann** [cn-uofbasel/ccn-lite#380]
There used to be support for OMNet++ in Release [0.3.0](https://github.com/cn-uofbasel/ccn-lite/releases/tag/0.3.0). Unfortunately, CCN-lite V2 has no support anymore (#125). Is anyone working on a reintegration?

**Comment by blacksheeep** [comment]
We would like to add support for NS-3, since OMNet++ is a little bit old.

But at the moment we do not have manpower to do so.
