### ISSUE TITLE
reduce all branches to master

### ISSUE THREAD

**Issue by sjmackenzie** [cn-uofbasel/ccn-lite#41]
Having topic branches on the canonical repo creates stale code.

Please could a development contract be adopted which mandates all code goes into master via pull requests. Preferably adopting something like: http://rfc.zeromq.org/spec:22 . This approach in effect turns the codebase into a kind of wiki driven development, it gets more eyeballs using master and fixing errors as they happen. Much like the approach they use in OpenBSD.

Please throw away all these useless branches.

**Comment by blacksheeep** [comment]
V2 is now in master, containing the latest code. Just can't remove all old branches for legacy reasons
