### ISSUE TITLE
Fail to compile with the master branch under Ubuntu 14.04

### ISSUE THREAD

**Issue by wufucious** [cn-uofbasel/ccn-lite#49]
Hello. I am trying to compiling and install ccn-lite on my Ubuntu 14.04. My kernel version is 3.19.0-25-generic. I follow all instruction from https://github.com/cn-uofbasel/ccn-lite/blob/master/doc/README-kernel.md and https://github.com/cn-uofbasel/ccn-lite/blob/master/doc/README-unix.md.  I set all parameters needed in my ~/.bashrc.

I am able to compile the 0.0.3 release version in my Ubuntu. But when I try the latest version of the master branch, something strange happen. 

wufucious@wufucious:~/ccn-lite-master/src$ make all
*** Configuring for Linux ***
*** With Linux Kernel ***
make modules
*** Configuring for Linux ***
*** With Linux Kernel ***
make[1]: Entering directory `/home/wufucious/ccn-lite-master/src'
make -C /lib/modules/`uname -r`/build M=`pwd` V=1 modules
make[2]: Entering directory `/usr/src/linux-headers-3.19.0-25-generic'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
	echo >&2;							\
	echo >&2 "  ERROR: Kernel configuration is invalid.";		\
	echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
	echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
	echo >&2 ;							\
	/bin/false)
mkdir -p /home/wufucious/ccn-lite-master/src/.tmp_versions ; rm -f /home/wufucious/ccn-lite-master/src/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/home/wufucious/ccn-lite-master/src
*** Configuring for Linux ***
*** With Linux Kernel ***
  gcc -Wp,-MD,/home/wufucious/ccn-lite-master/src/.ccn-lite-lnxkernel.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/4.8/include  -I./arch/x86/include -Iarch/x86/include/generated/uapi -Iarch/x86/include/generated  -Iinclude -I./arch/x86/include/uapi -Iarch/x86/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -m64 -mno-80387 -mno-fp-ret-in-387 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -DCC_HAVE_ASM_GOTO -g -std=gnu99  -DMODULE  -D"KBUILD_STR(s)=#s" -D"KBUILD_BASENAME=KBUILD_STR(ccn_lite_lnxkernel)"  -D"KBUILD_MODNAME=KBUILD_STR(ccn_lite_lnxkernel)" -c -o /home/wufucious/ccn-lite-master/src/.tmp_ccn-lite-lnxkernel.o /home/wufucious/ccn-lite-master/src/ccn-lite-lnxkernel.c
In file included from /home/wufucious/ccn-lite-master/src/ccn-lite-lnxkernel.c:49:0:
/home/wufucious/ccn-lite-master/src/ccnl-core.h:90:9: error: duplicate member ‘sock’
     int sock;
         ^
In file included from /home/wufucious/ccn-lite-master/src/ccnl-os-time.c:25:0,
                 from /home/wufucious/ccn-lite-master/src/ccn-lite-lnxkernel.c:110:
/home/wufucious/ccn-lite-master/src/ccnl-headers.h:7:22: fatal error: sys/time.h: No such file or directory
 #include <sys/time.h>
                      ^
compilation terminated.
make[3]: *** [/home/wufucious/ccn-lite-master/src/ccn-lite-lnxkernel.o] Error 1
make[2]: *** [_module_/home/wufucious/ccn-lite-master/src] Error 2
make[2]: Leaving directory `/usr/src/linux-headers-3.19.0-25-generic'
make[1]: *** [modules] Error 2
make[1]: Leaving directory `/home/wufucious/ccn-lite-master/src'
make: *** [ccn-lite-lnxkernel] Error 2

Why? How to fix it?
Thanks very much.

**Comment by blacksheeep** [comment]
Hi,
sorry for the delay, I fixed the compiling error, and the kernel mod work on my machine again.

Best
Chris
