### ISSUE TITLE
the cache in  ccn-lite (python ,API )

### ISSUE THREAD

**Issue by pengminjiong** [cn-uofbasel/ccn-lite#62]
I try to use python API to build my own application (https://github.com/cn-uofbasel/ccn-lite/tree/master/test/py)

but I found that  after I changed (Https://github.com/cn-uofbasel/ccn-lite/blob/master/src/py/pubfunc/myNamedFunctions.py) the myNamedFunctions.py file, I still get the same content from the function.

for example : change   def returnHelloWorld():
                                     return "Hello World"         to return "others"

after changed the return value, I still got the same reply("Hello world", not "others").
 then I checked the log , if " face_remove relay=****** "  is done, my changes in myNamedFunctions.py  will soon become available
I also stopped add content to cache in "ccnl-core.c"
how to eliminate  the old return value after I changed the  myNamedFunctions.py ?
I need help.

**Comment by blacksheeep** [comment]
Did you restart the Python part, after chancing the function? This will be
required.
Try to chance the function name.

Best
Christopher


2016-03-15 16:45 GMT+01:00 pengminjiong <notifications@github.com>:

> I try to use python API to build my own application (
> https://github.com/cn-uofbasel/ccn-lite/tree/master/test/py)
>
> but I found that after I changed (
> Https://github.com/cn-uofbasel/ccn-lite/blob/master/src/py/pubfunc/myNamedFunctions.py)
> the myNamedFunctions.py file, I still get the same content from the
> function.
>
> for example : change def returnHelloWorld():
> return "Hello World" to return "others"
>
> after changed the return value, I still got the same reply("Hello world",
> not "others").
> then I checked the log , if " face_remove relay=****** " is done, my
> changes in myNamedFunctions.py will soon become available
> I also stopped add content to cache in "ccnl-core.c"
> how to eliminate the old return value after I changed the
> myNamedFunctions.py ?
> I need help.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cn-uofbasel/ccn-lite/issues/62
>



-- 
Christopher Scherb, MSc
University of Basel
Computer Network Group
Room 02.001
Spiegelgasse 1
CH-4051 Basel, Switzerland
E-Mail: christopher.scherb@unibas.ch

**Comment by pengminjiong** [comment]
thank you.
you can close this issue.

best regards
peng minjiong
