### ISSUE TITLE
[patch] ccn-lite-relay: simultaneously use IPv4 and IPv6

### ISSUE THREAD

**Issue by bahlgren** [cn-uofbasel/ccn-lite#77]
Hi!

We had the need for relaying CCN messages between IPv4 and IPv6, so I made the attached modifications to ccn-lite-relay.c and needed support files to enable simultaneous use of IPv4 and IPv6.

This "works for me", but is by no means perfect. If you are interested in incorporating the code, but have feedback, I would be happy to make some further work on it. I have for instance deliberately not changed indentation in some places in order to minimise the diff.

(Let me know if it is more convenient for you to pull the code from my repo instead.)

Bengt

[0001-WIP-on-enabling-use-of-UDP-IPv4-and-UDP-IPv6-faces-s.patch.txt](https://github.com/cn-uofbasel/ccn-lite/files/307179/0001-WIP-on-enabling-use-of-UDP-IPv4-and-UDP-IPv6-faces-s.patch.txt)
[0002-Completed-changes-for-simultaneous-USE_IPV4-and-USE_.patch.txt](https://github.com/cn-uofbasel/ccn-lite/files/307182/0002-Completed-changes-for-simultaneous-USE_IPV4-and-USE_.patch.txt)

**Comment by blacksheeep** [comment]
Hi
look good.
Could you send this as pull request? 

Thanks
Christopher

**Comment by blacksheeep** [comment]
Or wait, I will just apply this, it's fine as it is

Thanks
Christopher

2016-06-09 17:00 GMT+02:00 Bengt Ahlgren <notifications@github.com>:

> Hi!
>
> We had the need for relaying CCN messages between IPv4 and IPv6, so I made
> the attached modifications to ccn-lite-relay.c and needed support files to
> enable simultaneous use of IPv4 and IPv6.
>
> This "works for me", but is by no means perfect. If you are interested in
> incorporating the code, but have feedback, I would be happy to make some
> further work on it. I have for instance deliberately not changed
> indentation in some places in order to minimise the diff.
>
> (Let me know if it is more convenient for you to pull the code from my
> repo instead.)
>
> Bengt
>
> 0001-WIP-on-enabling-use-of-UDP-IPv4-and-UDP-IPv6-faces-s.patch.txt
> <https://github.com/cn-uofbasel/ccn-lite/files/307179/0001-WIP-on-enabling-use-of-UDP-IPv4-and-UDP-IPv6-faces-s.patch.txt>
> 0002-Completed-changes-for-simultaneous-USE_IPV4-and-USE_.patch.txt
> <https://github.com/cn-uofbasel/ccn-lite/files/307182/0002-Completed-changes-for-simultaneous-USE_IPV4-and-USE_.patch.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cn-uofbasel/ccn-lite/issues/77>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADeQ_daIZnHc6YjtbVhyRzXRkESOjgjhks5qKCqTgaJpZM4IyEbE>
> .
>



-- 
Christopher Scherb, MSc
University of Basel
Computer Network Group
Room 02.001
Spiegelgasse 1
CH-4051 Basel, Switzerland
E-Mail: christopher.scherb@unibas.ch

**Comment by blacksheeep** [comment]
applied
