### ISSUE TITLE
Import inet.linklayer.IwiredNic

### ISSUE THREAD

**Issue by shreyas9** [cn-uofbasel/ccn-lite#80]
Am running omnet++ in windows 

Error says imported NED type not found: 'inet.linklayer.IwiredNic'

and also theirs a problem in inet/common

**Comment by blacksheeep** [comment]
Hi, sorry for late reply.
CCN-Lite has no Windows Support for now.

**Comment by shreyas9** [comment]
Hey,
Its okay i used ccnx for my project, Thank you for replying
